disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicit_return
  - modifier_order
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

included:
  - Translit

excluded:
  - TranslitTests
  - TranslitUITests
  - DerivedData

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20

reporter: "xcode"
